import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
      },
    },
  },
  plugins: [],
  safelist: [
    "bg-black",
    "text-white",
    "min-h-screen",
    "flex",
    "items-center",
    "justify-center",
    "p-4",
    "w-full",
    "max-w-md",
    "bg-gray-900",
    "border",
    "border-gray-800",
    "rounded-lg",
    "text-center",
    "mb-6",
    "text-4xl",
    "font-bold",
    "mb-4",
    "text-2xl",
    "text-gray-400",
    "space-y-4",
    "block",
    "text-gray-300",
    "text-sm",
    "font-medium",
    "mb-2",
    "px-3",
    "py-2",
    "bg-gray-800",
    "border-gray-700",
    "rounded-md",
    "placeholder-gray-400",
    "focus:outline-none",
    "focus:ring-2",
    "focus:ring-blue-500",
    "bg-blue-600",
    "hover:bg-blue-700",
    "transition-colors",
    "mt-6",
    "text-blue-400",
    "hover:text-blue-300",
    "font-semibold",
  ],
};

export default config;
